name: Run unit tests

on: [ pull_request ]

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      JAVA_VERSION: 17

    steps:
      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: ${{ env.JAVA_VERSION }}
      - name: Checkout main repository
        uses: actions/checkout@v2
      - name: Execute unit tests
        run: mvn clean test
      - name: Publish test report
        uses: mikepenz/action-junit-report@v2
        if: always()
        with:
          report_paths: '**/target/surefire-reports/TEST-*.xml'